name: Build Node binaries for Linux static

on:
  push:
  workflow_dispatch:

jobs:
  linuxstatic:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        target-node: [14, 16, 18, 19]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PKG_FETCH_OPTION_n=node${{ matrix.target-node }}
            PKG_FETCH_OPTION_p=linuxstatic
          context: .
          file: ./Dockerfile.alpine
          outputs: type=tar,dest=../out.tar

      - name: Extract binaries from Docker image
        run: |
          tar xvf ../out.tar root/pkg-fetch/dist

      - name: Check if binary is compiled
        id: check_file
        run: |
          (test -f root/pkg-fetch/dist/*.sha256sum && echo ::set-output name=EXISTS::true) || echo ::set-output name=EXISTS::false

      - uses: actions/upload-artifact@v2
        if: steps.check_file.outputs.EXISTS == 'true'
        with:
          name: node${{ matrix.target-node }}-linuxstatic-x64
          path: root/pkg-fetch/dist/*
